#!/usr/bin/env bash
# Fail fast: a broken build or upload must never move the marketplace tags.
set -eu

releasenotes="This release was generated by Goreleaser!"

# Correctly capture the latest git tag into the variable
echo "Getting the latest tag..."
taglatest=$(git describe --tags --abbrev=0)

# Run GoReleaser skipping SCM validation and publishing
echo "Running Goreleaser..."
goreleaser release --clean --skip=publish

# Create the release and upload whatever files exist in the dist folder
echo "Uploading release binaries to github via the gh CLI..."
gh release create "$taglatest" \
  ./dist/*.tar.gz \
  ./dist/*.zip \
  ./dist/*.txt \
  ./dist/metadata.json \
  --title "$taglatest" \
  --notes "$releasenotes"

# Point the marketplace float tags (vX, vX.Y) at this release.
echo "Moving marketplace tags..."
sh scripts/release-action.sh "$taglatest"
